development:
  adapter: postgresql
  encoding: unicode
  database: myapp-development
  pool: 5
  port: 5432
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: myapp-test
  pool: 5
  port: 5432
  host: localhost